### ISSUE TITLE
Documentation idea: relation to foldMap

### ISSUE THREAD

**Issue by chris-martin** [tfausak/list-singleton#1]
I remember when I started using Haskell I was a bit confused why *singleton* functions need to exist, because how often do I really need a single-item collection? My path to figuring this out showed, I think, how singleton is an important stepping stone to understanding how we work with immutable data structures: we often build larger structures by monoidally joining smaller ones, and the smallest nontrivial collection is a singleton.

It might be helpful to add to the `singleton` documentation some examples of `foldMap singleton`, an expression so useful that I think a learner ought to memorize it. `foldMap singleton` is sort of the universal converter between collections:

```haskell
>>> import qualified Data.Set as Set
>>> import qualified Data.List.Singleton as List
>>> a = Set.fromList [1,2,3]
>>> b = [4,5,6,5]
>>> foldMap Set.singleton b
fromList [4,5,6]
>>> foldMap List.singleton b
[4,5,6,5]
```

**Comment by tfausak** [comment]
Ah, great idea! I took it for granted that readers would already know why they want `singleton`. I think it's a great idea to add some rationale. 

I'd happily accept a PR for this, or I can get around to it in the next couple days.
